name: Send Surgery Reminder

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 23 * * *'   # 한국시간 08:30 = UTC 23:30
  workflow_dispatch:        # ✅ 여기로 내리기


jobs:
  send-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run reminder script
  run: node sendReminder.cjs
  env:
    FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}

